_target_: models.score_model.Tor_Model

model:
  lm_embed_dim: 1303 # 1280 (ESM) + 21 (One-Hot) + 1 (SASA) + 1 (Interface)
  positional_embed_dim: 66 # 66 (Residue)
  spatial_embed_dim: 60 # 24 (phi) + 24 (psi) + 12 (omega)
  contact_embed_dim: 1 # 1 (contact)
  node_dim: 256
  edge_dim: 128
  inner_dim: 32
  depth: 4
  dropout: 0.1
  cut_off: 50.0
  normalize: True

diffuser:
  r3:
    min_sigma: 0.1
    max_sigma: 50.0
    schedule: VE
  so3:
    num_omega: 1000
    num_sigma: 1000
    min_sigma: 0.1
    max_sigma: 1.5
    schedule: logarithmic
    cache_dir: .cache/
    use_cached_score: True
  tor:
    num_omega: 1000
    num_sigma: 1000
    min_sigma: 0.1
    max_sigma: 1.5
    schedule: logarithmic
    cache_dir: .cache/
    use_cached_score: True
    
experiment:
  lr: 1e-4
  weight_decay: 0.0
  grad_energy: True
  perturb_tr: False
  perturb_rot: False
  perturb_tor: True
  separate_energy_loss: True
  separate_tr_loss: True
  separate_rot_loss: True
  separate_tor_loss: True

