_target_: utils.utils.TorDataModule


data_dir: /Users/scanner1/Downloads/capdock/pdb_pre/
full_list: /Users/scanner1/Downloads/capdock/pdb_pre/tor_bois.txt
batch_size: 1
num_workers: 6
pin_memory: True