name: capdock
channels:
  - conda-forge
dependencies:
  - bzip2
  - ca-certificates
  - ld_impl_linux-64
  - libffi
  - libsqlite
  - libuuid
  - libxcrypt
  - libzlib
  - ncurses
  - openssl
  - pip
  - python=3.9.19
  - readline
  - setuptools
  - tk
  - tzdata
  - wheel
  - xz
  - pip:
      - aiohttp==3.9.5
      - aiosignal==1.3.1
      - async-timeout==4.0.3
      - attrs==23.2.0
      - biopython==1.83
      - certifi==2022.12.7
      - charset-normalizer==2.1.1
      - cmake==3.25.0
      - colorlog==6.8.2
      - dm-tree==0.1.6
      - einops==0.8.0
      - filelock==3.13.1
      - frozenlist==1.4.1
      - fsspec==2024.6.0
      - hydra-colorlog==1.2.0
      - idna==3.4
      - jinja2==3.1.3
      - joblib==1.4.2
      - lightning==2.2.5
      - lightning-utilities==0.11.2
      - lit==15.0.7
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - mdurl==0.1.2
      - mpmath==1.3.0
      - multidict==6.0.5
      - networkx==3.2.1
      - numpy==1.26.3
      - packaging==24.1
      - pillow==10.2.0
      - psutil==5.9.8
      - pygments==2.18.0
      - pyparsing==3.1.2
      - pytorch-lightning==2.2.5
      - pyyaml==6.0.1
      - requests==2.28.1
      - rich==13.7.1
      - scikit-learn==1.5.0
      - scipy==1.13.1
      - six==1.16.0
      - sympy==1.12
      - threadpoolctl==3.5.0
      - torch==2.0.1+cu118
      - torch-geometric==2.5.3
      - torchaudio==2.0.2+cu118
      - torchmetrics==1.4.0.post0
      - torchvision==0.15.2+cu118
      - tqdm==4.66.4
      - triton==2.0.0
      - typing-extensions==4.9.0
      - urllib3==1.26.13
      - yarl==1.9.4
